apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "marcosfalves/hello-go:v7.3"
          resources:
            requests: #mínimo (Reservando os recursos do cluster para o pod)
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 3
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 3
            failureThreshold: 1
            #initialDelaySeconds: 10 #Tempo de espera antes de começar as verificações

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            periodSeconds: 5 #Intervalo de tempo para executar uma verificação
            failureThreshold: 1 #Quantas vezes precisa dar errado para marcar o container como não saudável=
            timeoutSeconds: 1 #Tempo máximo de espera da requisição de verificação (Valores baixos, pois normalmente esse endpoint responde rápido)
            successThreshold: 1 #Quantas vezes precisa dar certo para marcar o container como saudável
            #initialDelaySeconds: 15

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"
